### ISSUE TITLE
Debug of Exudyn

### ISSUE THREAD

**Issue by Jiang-Cui** [jgerstmayr/EXUDYN#34]
Dear professor,

I re-installed the Exudyn today, but an error occured. Whe I click the "debug" in VS2022, the python interface just flashes by. When I click "start execution without debugging", the following error are shown. 

<img width="735" alt="debug_error" src="https://user-images.githubusercontent.com/84257410/217516927-5894b155-88a5-4362-bdfe-7c05c48cd386.PNG">

I use VS2022 and python 3.9 to debug. I have successfully installed and debugged Exudyn before, and the same procedure are repeated today but I cannot debug.

**Comment by jgerstmayr** [comment]
I unfortunately have no access to VS2022, I only use VS2017 because this is the only version that is reliable regarding Eigen and other numerical libraries.

If you did not make any changes to Exudyn, then it is a migration problem to VS2022.
You will have to adapt the project settings if you migrate from VS2017 to VS2022. It may also be necessary to use another way to load exudynCPP.pyd . The current way it is done is based on the VS2017 recommendations.

It may also be the case that there is a compilation error. If this happens (e.g. if not all functions are correctly compiled in the .pyd DLL, it will show the exact error that you show). More information can be usually obtained under linux (e.g. using WSL).

**Comment by Jiang-Cui** [comment]
Thank you, Prof. Johannes Gerstmayr!
