### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Jiang-Cui** [jgerstmayr/EXUDYN#50]
Dear professor,

Before, I have successfully installed Exudyn and use the C++ source code in the platform of Windows 10, VS2017, and python 3.7.9.

I now install the Exudyn in Windows 11 using the same steps using VS2017 and python 3.7.9. The cpp project can be successfully  compiled, but an error occured in debugging process. When I click "start execution without debugging" to debug the pytest.py, the following error are shown. This same error occurs before when I used VS2022. 
![4a9932ffcf17be6b93d9c94a58d209b](https://github.com/jgerstmayr/EXUDYN/assets/84257410/1a20afdd-c996-4df4-9efa-2d9f2dd386c2)

Coud you help me to solve this error? Thank you very much!

**Comment by Jiang-Cui** [comment]
Thank you very much, Professor! I have copied the new exudynCPP.pyd to the file where the pytest.py is located, but the error occurred in Windows 11. Is there another way to solve the error?

**Comment by Jiang-Cui** [comment]
Dear Professor,

I have simplify the __init__.py, and add print(sys.version). It seems that this cannot work, as shows

![b51d587bcc1f69219f087695652c4d3](https://github.com/jgerstmayr/EXUDYN/assets/84257410/53463af0-62dd-443d-b9af-8ab62753e1e7)

**Comment by jgerstmayr** [comment]
Now you can just check if 3.7 64bits agrees with your compiled .pyd version (check your VS2017 settings). 

Another possible issue is that you changed something in exudyn. Did you? Commonly, if you are doing something wrong in the interface (e.g. failing to supply a API-function in the library correctly), this will raise a DLL load failed message without further information.   A workaround is to use a linux compilation, where gdb shows the missing API function.

Otherwise, it is a problem with directory settings in VS2017/Windows11 and you have to look there to resolve problems. This is not an exudyn problem anymore.

**Comment by Jiang-Cui** [comment]
Dear Prof. Gerstmayr,

Thanks for you reply. I have downloaded the latest code from github, the "ModuleNotFoundError" problem dose not exist. Thank you very much!
