### ISSUE TITLE
Wrong type of pyObject argument

### ISSUE THREAD

**Issue by ManuelZ** [jgerstmayr/EXUDYN#64]
`AddMarker` supposedly receives a `dict`:

[Source](https://github.com/jgerstmayr/EXUDYN/blob/05de550b733ae2a11f0d4db4bb17b88725e95b71/main/pythonDev/exudyn/__init__.pyi#L1457)
```
@overload
    def AddMarker(self, pyObject: dict) -> MarkerIndex: ...
```

But it really receives a Python object:

[Source](https://github.com/jgerstmayr/EXUDYN/blob/05de550b733ae2a11f0d4db4bb17b88725e95b71/main/src/Autogenerated/pybind_manual_classes.h#L238)
```
.def("AddMarker", &MainSystem::AddMainMarkerPyClass, "add a marker...", py::arg("pyObject"))
```

[Source](https://github.com/jgerstmayr/EXUDYN/blob/05de550b733ae2a11f0d4db4bb17b88725e95b71/main/src/Main/MainSystem.h#L282)
```
//! Add a MainMarker with a python class
MarkerIndex AddMainMarkerPyClass(const py::object& pyObject);
```

Indeed, there exists a method that adds a marker when passed a dict, but when I search for it in the codebase, I don't see it being used.

[Source](https://github.com/jgerstmayr/EXUDYN/blob/05de550b733ae2a11f0d4db4bb17b88725e95b71/main/src/Main/MainSystem.h#L280)
```
//! this is the hook to the object factory, handling all kinds of objects, nodes, ...
Index AddMainMarker(const py::dict& d);
```

The same seems to happen with `AddObject`, `AddNode`, `AddLoad` and `AddSensor`.

This is the typing error that I'm seeing:

```
Argument of type "MarkerBodyRigid" cannot be assigned to parameter "pyObject" of type "dict[Unknown, Unknown]" in function "AddMarker"
  "MarkerBodyRigid" is incompatible with "dict[Unknown, Unknown]"Pylance[reportArgumentType]
```

I guess a better type could be the `object` [type](https://mypy.readthedocs.io/en/stable/builtin_types.html#simple-types).

**Comment by jgerstmayr** [comment]
This may look like a confusion, but is done by design.
The interface requires a dictionary. However, usually, you are not creating the dictionary, but you are using an interface class such as ObjectRigidBody. This class provides a conversion to a dictionary, which includes type checks and alleviates the interfacing between Python and C++. In order to catch errors of the users easier when they provide something else than a dictionary, we take the most general py::object which then can give a "readable" error message.

I understand that this may confuse the very interested reader of the code, but this is done by design. So, I will change the type hint to py::object which should resolve the typing errors.

**Comment by jgerstmayr** [comment]
A short request: could you try to change pyObject: dict into pyObject: Any in the .pyi file of your site-packages for a trial? This should resolve the issue and it would not cause a major confusion for the user, as users should know what args to use in AddObject, AddNode, etc.

If this works for PyLance (and on my local version), I would just change this in the repo ...

**Comment by ManuelZ** [comment]
I've tested it and it works when I replace the type and make it `Any` in `exudyn\__init__.pyi`.

**Comment by jgerstmayr** [comment]
ok, will be done within version 1.8.19.
Thanks for your help!

**Comment by ManuelZ** [comment]
Thanks. Your welcome!
